### ISSUE TITLE
Build instructions for Linux?

### ISSUE THREAD

**Issue by teccheck** [Goobwabber/MultiQuestensions#18]
It would be super awesome if you could add build instructions for Linux and vscode. I saw that the github action runs on ubuntu so I guess building works on linux. Awesome work btw :wink:

**Comment by michael-r-elp** [comment]
If you're talking about the current dev branch Update-1.21.0 then you'll need to get MultiplayerCore.Quest first a pre-built shared library can be found under the actions tab of the MultiplayerCore.Quest repository the header files will require you to download the source code though.

Otherwise it's just the basic setup for quest modding, you should easily find instructions to setup a dev environment or be able to ask in the quest-mod-dev channel within the BSMG discord

Also the dev branch build is not supported by the current public BT servers

**Comment by teccheck** [comment]
Ok, thank you :+1:
